stages:
  - build
  - test
  - deploy

build_macOS:
  stage: build
  script:
  - set -o pipefail && xcodebuild build-for-testing -parallelizeTargets -project Result.xcodeproj -scheme Result-macOS -destination "platform=OS X" | xcpretty

build_iOS:
  stage: build
  script:
  - set -o pipefail && xcodebuild build-for-testing -parallelizeTargets -project Result.xcodeproj -scheme Result-iOS -destination "platform=iOS Simulator,name=iPhone 8" | xcpretty

build_watchOS:
  stage: build
  script:
  - set -o pipefail && xcodebuild build-for-testing -parallelizeTargets -project Result.xcodeproj -scheme Result-watchOS -destination "platform=watchOS Simulator,name=Apple Watch - 38mm" | xcpretty

build_tvOS:
  stage: build
  script:
  - set -o pipefail && xcodebuild build -parallelizeTargets -project Result.xcodeproj -scheme Result-tvOS -destination "platform=tvOS Simulator,name=Apple TV" | xcpretty

## -----------------------------

test_macOS:
  stage: test
  script:
  - set -o pipefail && xcodebuild test-without-building -project Result.xcodeproj -scheme Result-macOS -destination "platform=OS X" | xcpretty

test_iOS:
  stage: test
  script:
  - set -o pipefail && xcodebuild test-without-building -project Result.xcodeproj -scheme Result-iOS -destination "platform=iOS Simulator,name=iPhone 8" | xcpretty

test_tvOS:
  stage: test
  script:
  - set -o pipefail && xcodebuild test-without-building -project Result.xcodeproj -scheme Result-tvOS -destination "platform=tvOS Simulator,name=Apple TV" | xcpretty
