stages:
  - build
  - test
  - deploy

build_macOS:
  tags:
    - Knowhere-MBP.local
  only:
    refs:
      - master
  stage: build
  script:
  - xcodebuild build-for-testing -parallelizeTargets -project Result.xcodeproj -scheme Result-macOS -destination "platform=OS X"

build_iOS:
  tags:
    - Knowhere-MBP.local
  only:
    refs:
      - master
  stage: build
  script:
  - xcodebuild build-for-testing -parallelizeTargets -project Result.xcodeproj -scheme Result-iOS -destination "platform=iOS Simulator,name=iPhone 8"

build_watchOS:
  tags:
    - Knowhere-MBP.local
  only:
    refs:
      - master
  stage: build
  script:
  - xcodebuild build -parallelizeTargets -project Result.xcodeproj -scheme Result-watchOS -destination "platform=watchOS Simulator,name=Apple Watch - 38mm"

build_tvOS:
  tags:
    - Knowhere-MBP.local
  only:
    refs:
      - master
  stage: build
  script:
  - xcodebuild build -parallelizeTargets -project Result.xcodeproj -scheme Result-tvOS -destination "platform=tvOS Simulator,name=Apple TV"

## -----------------------------

test_macOS:
  tags:
    - Knowhere-MBP.local
  only:
    refs:
      - master
  stage: test
  script:
  - set -o pipefail && xcodebuild test -project Result.xcodeproj -scheme Result-macOS -destination "platform=OS X" | xcpretty

test_iOS:
  tags:
    - Knowhere-MBP.local
  only:
    refs:
      - master
  stage: test
  script:
  - set -o pipefail && xcodebuild test -project Result.xcodeproj -scheme Result-iOS -destination "platform=iOS Simulator,name=iPhone 8" | xcpretty

test_tvOS:
  tags:
    - Knowhere-MBP.local
  only:
    refs:
      - master
  stage: test
  script:
  - set -o pipefail && xcodebuild test -project Result.xcodeproj -scheme Result-tvOS -destination "platform=tvOS Simulator,name=Apple TV" | xcpretty
